name: Frak Windoze
on: workflow_dispatch

jobs:
    build:
      name: Get Frakking Windoze
      runs-on: windows-latest
      steps:
###        - name: S0a
###          run: dir/s/b/od *.ps1 & dir C:\ & dir D:\ & pwd
###          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .\Fido
###        - name: S0b
###          run: dir/s/b/od *.ps1 & pwd
###          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .\t11b
            repository: alimas7/tiny11builder
###            ref: refs/heads/release
        - name: S1
          run: .\Fido\Fido.ps1 -Win 11 -Ed Pro -Lang English ### -GetUrl
          shell: powershell
###        - name: S2
###          run: dir/s/b/od & pwd
###          shell: cmd /c {0}
        - name: S3
          run: .\t11b\tiny11Coremaker.ps1
        - name: S4
          if: always()
          run: dir/s/b D:\ & pwd
          shell: cmd /c {0}
###        - name: S5
###          if: always()
###          run: dir/s/b E:\ & pwd
###          shell: cmd /c {0}
        - name: S6
          uses: actions/upload-artifact@v4
          with:
            name: t11b-${{ matrix.runs-on }}
            path: |
              D:\
              !D:\a\Fido\Fido\Win11_23H2_English_x64v2.iso
            compression-level: 9
