name: WTF
on: workflow_dispatch

jobs:
    build:
      name: WTFH
      runs-on: windows-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: S4b
          if: always()
          run: pwd & C:/msys64/usr/bin/find.exe C:/msys64 -type f | C:/msys64/usr/bin/xz.exe -9 > 01.c.msys64.xz

        - name: S4c
          if: always()
          run: pwd & C:/msys64/usr/bin/find.exe D:/ -type f | C:/msys64/usr/bin/xz.exe -9 > 02.d.xz

        - name: S4d
          if: always()
          run: pwd & C:/msys64/usr/bin/find.exe C:/ -type f | C:/msys64/usr/bin/xz.exe -9 > 03.c.xz

        - name: S6
          uses: actions/upload-artifact@v4
          with:
            name: out1
            path: |
              01.c.msys64.xz
              02.d.xz
              03.c.xz
