name: Frak Windoze
on: workflow_dispatch

jobs:
    build:
      name: Get Frakking Windoze
      runs-on: windows-latest
      steps:
        - name: S0a
          run: dir/od & pwd
          shell: cmd /c {0}
        - uses: actions/checkout@v4
            with:
            path: .
        - name: S0b
          run: dir/od & pwd
          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .
            repository: alimas7/tiny11builder
###            ref: refs/heads/release
###        - name: S1
###          run: .\Fido.ps1 -Win 11 -Ed Pro -Lang English ### -GetUrl
        - name: S2
          run: dir/od & pwd
          shell: cmd /c {0}
###        - name: S3
###          run: .\tiny11Coremaker.ps1
