name: Frak Windoze
on: workflow_dispatch

jobs:
    build:
      name: Get Frakking Windoze
      runs-on: windows-latest
      steps:
        - name: S0a
          run: dir/s/b/od *.ps1 & pwd
          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .\Fido
        - name: S0b
          run: dir/s/b/od *.ps1 & pwd
          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .\t11b
            repository: alimas7/tiny11builder
###            ref: refs/heads/release
        - name: S1
          run: .\Fido\Fido.ps1 -Win 11 -Ed Pro -Lang English ### -GetUrl
        - name: S2
          run: dir/s/b/od & pwd
          shell: cmd /c {0}
        - name: S3
          run: .\t11b\tiny11Coremaker.ps1
        - name: S4
          run: dir/s/b/od & pwd
          shell: cmd /c {0}
