name: Frak Windoze
on: workflow_dispatch

jobs:
    build:
      name: Get Frakking Windoze
      runs-on: windows-latest
      defaults:
        run:
          shell: bash
      steps:
###        - name: S0a
###          run: dir/s/b/od *.ps1 & dir C:\ & dir D:\ & pwd
###          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .\Fido
###        - name: S0b
###          run: dir/s/b/od *.ps1 & pwd
###          shell: cmd /c {0}
        - uses: actions/checkout@master
          with:
            path: .\t11b
            repository: alimas7/tiny11builder
###            ref: refs/heads/release
        - name: S1
          run: Set-PSDebug -Trace 1 ; .\Fido\Fido.ps1 -Win 11 -Ed Pro -Lang English ### -GetUrl
          shell: powershell
###        - name: S2
###          run: dir/s/b/od & pwd
###          shell: cmd /c {0}
        - name: S3
          run: .\t11b\tiny11Coremaker.ps1
          shell: powershell
        - name: S3a
          uses: actions/upload-artifact@v4
          with:
            name: t11b-0
            path: |
              D:\a\Fido\Fido\t11b\tiny11.iso
              D:\a\Fido\Fido\t11b\tiny11.log
            compression-level: 9
        - name: S4b
          if: false ###always()
          run: pwd; C:/msys64/usr/bin/find.exe C:/msys64 -type f | C:/msys64/usr/bin/xz.exe -9 > 01.c.msys64.xz

        - name: S4c
          if: false ###always()
          run: pwd; C:/msys64/usr/bin/find.exe D:/ -type f | C:/msys64/usr/bin/xz.exe -9 > 02.d.xz
        - name: S4x
          if: false ###always()
          uses: actions/upload-artifact@v4
          with:
            name: out1
            path: |
              01.c.msys64.xz
              02.d.xz
            compression-level: 9
        - name: S4d
          if: false ###always()
          run: pwd; C:/msys64/usr/bin/find.exe C:/ -type f | C:/msys64/usr/bin/xz.exe -9 > 03.c.xz
###        - name: S5
###          if: always()
###          run: dir/s/b E:\ & pwd
###          shell: cmd /c {0}
        - name: S6
          if: false ###always()
          uses: actions/upload-artifact@v4
          with:
            name: out2
            path: 03.c.xz
            compression-level: 9
###        - name: S7
###          uses: actions/upload-artifact@v4
###          with:
###            name: t11b-2
###            path: |
###              D:\
###              !D:/*.tmp
###              !D:\a\Fido\Fido\Win11_23H2_English_x64v2.iso
###              !D:\a\Fido\Fido\t11b\tiny11.iso
###              !D:\a\Fido\Fido\t11b\tiny11.log
###            compression-level: 9
