name: Frak Windoze
on: [workflow_dispatch]

jobs:
    build:
      name: Get Frakking Windoze
      runs-on: windows-latest
      steps:
###        - uses: actions/checkout@v4
        - uses: actions/checkout@master
          with:
            name: alimas7/tiny11builder
            ref: refs/heads/release
        - name: S1
          run: notepad ### .\Fido.ps1 -Win 11 -Ed Pro -Lang English ### -GetUrl
        - name: S2
          run: dir/od
          shell: cmd /c {0}
        - name: S3
          run: notepad ### .\tiny11Coremaker.ps1
